version: '3.8'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./share:/tmp/wordpress-test-technique

volumes:
  db_data:
  wp-content:
  share:
